# Generated by Django 4.2.7 on 2024-07-26 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageprevu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
